version: '3'
services:
  db:
    build: "./db-docker"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  backend:
    build: .
    environment:
      PORT: "${PORT}"
      SOCKET_PORT: "${SOCKET_PORT}"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      CLIENT_URL: "${CLIENT_URL}"
      EMAIL: "${EMAIL}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
      - "8081:8081"